# Generated by Django 4.2 on 2023-04-12 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Properties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=30)),
                ('price', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('room_type', models.CharField(max_length=30)),
                ('bedrooms', models.CharField(max_length=30)),
                ('bathrooms', models.CharField(max_length=30)),
                ('house_type', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('image', models.ImageField(null=True, upload_to='images/')),
            ],
        ),
    ]
