# Generated by Django 4.2 on 2023-04-09 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_rename_satte_properties_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
